title: Syntacts

minima:
  date_format: "%b %-d, %Y"
  skin: classic
  social_links:
#     twitter: jekyllrb
    github:  mahilab
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCN0uGLNR3YiJck7zUk_XB7w
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

theme: minima

header_pages:
  - start.md
  - build.md
  - tutorials.md
  - amp.md
  - faq.md
